### ISSUE TITLE
Which Components?

### ISSUE THREAD

**Issue by ghost** [nopnop2002/OrangePi-ZERO-FAN-HAT#8]
Which Components do I need to buy for the PCB?

**Comment by nopnop2002** [comment]
Order to FusionPCB or Elecrow using Garbar file.

FusionPCB

http://support.seeedstudio.com/knowledgebase/articles/945502-how-to-place-a-fusion-pcb-order

https://www.seeedstudio.com/fusion_pcb.html


Elecrow

https://www.elecrow.com/download/Readme%20before%20ordering%20PCB%20online%20V1.2.pdf

https://www.elecrow.com/pcb-manufacturing.html

**Comment by ghost** [comment]
But they look like this, without any components...
![IMG_20190321_064645](https://user-images.githubusercontent.com/18703455/55056598-d0b63880-5066-11e9-9bb8-4bcecefb3e70.jpg)

**Comment by nopnop2002** [comment]
You have to supply other parts by yourself.
A necessary parts list is here.

https://github.com/nopnop2002/OrangePi-ZERO-FAN-HAT/blob/master/schematics.pdf

**Comment by ghost** [comment]
Do you know a good place to buy the parts?

**Comment by nopnop2002** [comment]
My recomendation is Ali Express.
https://www.aliexpress.com/

Sale will start from tomorrow.
